# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tiny Silos!
email: contact@tinysilos.com
description: >- # this means to ignore newlines until "baseurl:"
  A website dedicated to silo enthusiasts everywhere! ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tinysilos.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
